languageCode = 'en-us'
title = 'Ethan Sterling'
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
repoURL = 'https://github.com/EthanSterling04/EthanSterling04/'
description = "Ethan Sterling's Portfolio"
colorDark = '#121212'
colorLight = '#f7f7f7'
colorDarkAccent = '#FFB74D'
colorLightAccent = '#E65100'
images = ['android-chrome-512x512.png']
